// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnalysisSkeleton: typeof import('./components/Skeleton/AnalysisSkeleton.vue')['default']
    ApplicationCard: typeof import('./components/Card/ApplicationCard.vue')['default']
    Card: typeof import('./components/Card/index.vue')['default']
    ChartCard: typeof import('./components/Card/ChartCard.vue')['default']
    DarkSwitcher: typeof import('./components/ThemeSelect/components/darkSwitcher/index.vue')['default']
    DarkTheme: typeof import('./components/ThemeSelect/components/darkSwitcher/dark-theme.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Guide: typeof import('./components/Guide/index.vue')['default']
    LangSelect: typeof import('./components/LangSelect/index.vue')['default']
    LightTheme: typeof import('./components/ThemeSelect/components/darkSwitcher/light-theme.vue')['default']
    NewsCardItem: typeof import('./components/WorkBenchCard/news-card-item.vue')['default']
    ProjectCard: typeof import('./components/Card/ProjectCard.vue')['default']
    ProjectCardItem: typeof import('./components/WorkBenchCard/project-card-item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Src: typeof import('./components/Table/src/index.vue')['default']
    ThemeSelect: typeof import('./components/ThemeSelect/index.vue')['default']
    ToolTip: typeof import('./components/ToolTip/index.vue')['default']
    WorkBenchCard: typeof import('./components/WorkBenchCard/index.vue')['default']
    WorkbenchSkeleton: typeof import('./components/Skeleton/WorkbenchSkeleton.vue')['default']
  }
}

export {}
